---
title: "Retrieving Longitudinal and Repeating Structures"
author: Will Beasley [Biomedical & Behavior Methodology Core](https://www.ouhsc.edu/bbmc/team/), OUHSC Pediatrics
output:
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Retrieving Longitudinal and Repeating Structures}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
#| include = FALSE
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  tidy    = FALSE
)
```

Background
==================================================================

If your REDCap project is longitudinal or contains repeating measures, a single call to the API (or a single export through the browser) will return a dataset that is not readily analyzed.  Instead, the dataset will resemble Table 5.  This isn't because of a software bug, but because you haven't told the software how you would like it structured.  There isn't a great way to jam this multidimensional space into a rectangle of points.  Our advice for querying REDCap is the same as querying any database system: request datasets that have a natural "grain" and assemble them as to best fit your analyses.

If your project is not longitudinal and has not repeating measures, you can stop reading and simply call REDCapR's [redcap_read()].

Illustration of How Data Points are Structured
==================================================================

Suppose you have two patients (*i.e.*, "1" and "2") with three intake variables (*i.e.*, `height`, `weight`, and `bmi`).  If you record this on a piece of paper, it would probably look like Table 1.  The table's *grain* is "patient", because each row represents a distinct patient.  Understanding the grain of each structure below will help you understand how the structures are re-expressions of the same set of observations.

**Table 1: patient grain** is the most natural presentation of the six initial observations.

| `pt` | `height` | `weight` | `bmi` |
| ---: | -------: | -------: | ----: |
|    1 |      1.0 |     11.0 | 111.0 |
|    2 |      2.0 |     22.0 | 222.0 |

This patient-grain structure is how the data points are most comfortably inputted by humans into REDCap, and it is the default when exported through the browser and API.  However it is stored differently under the hood.

REDCap's flexibility is a driver of its success.  Once a research team learns REDCap, it can reuse the knowledge to capture anything from qqq to qqq.  But to achieve this flexibility in the world of REDCap and EMRs, data are stored along the observation grain.  In computer science, this is commonly called an EAV structure (which stands for entity-attribute-value).  The patient's ID is the entity, the variable type is the attribute, and the observed point is the value.  It can also be thought of as a "key-value store" nested within a patient (where "key" is a synonym of "attribute").  Notice that the two wider rows have morphed into six skinnier rows --one row per observation.

**Table 2: observation grain** is how REDCap and EMR databases store observations in their underlying database.

| `pt` | `key`  | `value` |
| ---: | :----- | ------: |
|    1 | height |     1.0 |
|    1 | weight |    11.0 |
|    1 | bmi    |   111.0 |
|    2 | height |     2.0 |
|    2 | weight |    22.0 |
|    2 | bmi    |   222.0 |

If the investigation gains a longitudinal or repeating component, it becomes necessary to include the dimension of time.  Suppose the protocols specifies five time points; the blood pressure instrument is captured at times 1, 2, & 3 while the laboratory instrument is captured at times 3 & 4.  If you record this on paper too, it's likely with two rectangles that resemble Tables 3a & 3b: one for vitals and one for labs.

**Table 3a: patient-time grain for `blood_pressure` instrument** is how

| `pt` | `time` | `sbp` | `dbp` |
| ---: | -----: | ----: | ----: |
|    1 |      1 |   1.1 |  11.1 |
|    1 |      2 |   1.2 |  11.2 |
|    1 |      3 |   1.3 |  11.3 |
|    2 |      1 |   2.1 |  22.1 |
|    2 |      2 |   2.2 |  22.2 |
|    2 |      3 |   2.3 |  22.3 |

**Table 3b: patient-time grain for `laboratory` instrument** is how

| `pt` | `time` | `lab` | `dose` |
| ---: | -----: | ----: | -----: |
|    1 |      3 |   aa3 | 1.3 mg |
|    1 |      4 |   aa4 | 1.4 mg |
|    2 |      3 |   bb3 | 2.3 mg |
|    2 |      4 |   bb4 | 2.4 mg |

When these measurements are added to REDCap's observation table, it resembles Table 4.  Two new columns are required to uniquely distinguish the instrument and its ordinal position.  These columns exist in Table 2, but are empty for those six intake rows.

**Table 4: observation grain for `blood_pressure` and `laboratory` instruments** is how...

| `pt` | `repeat`<br>`instrument` |`repeat`<br>`instance` | `key` | `value`  |
| ---: | -----------------------: | --------------------: | ----: | -------: |
|    1 | blood_pressure           |                     1 |   sbp |      1.1 |
|    1 | blood_pressure           |                     1 |   dbp |     11.1 |
|    1 | blood_pressure           |                     2 |   sbp |      1.2 |
|    1 | blood_pressure           |                     2 |   dbp |     11.2 |
|    1 | laboratory               |                     3 |   lab |      aa3 |
|    1 | laboratory               |                     3 |  conc |  1.3 ppm |
|    1 | blood_pressure           |                     3 |   sbp |      1.3 |
|    1 | blood_pressure           |                     3 |   dbp |     11.3 |
|    1 | laboratory               |                     4 |   lab |      aa4 |
|    1 | laboratory               |                     4 |  conc |  1.4 ppm |
|    2 | blood_pressure           |                     1 |   sbp |      2.1 |
|    2 | blood_pressure           |                     1 |   dbp |     22.1 |
|    2 | blood_pressure           |                     2 |   sbp |      2.2 |
|    2 | blood_pressure           |                     2 |   dbp |     22.2 |
|    2 | laboratory               |                     3 |   lab |      bb3 |
|    2 | laboratory               |                     3 |  conc |  2.3 ppm |
|    2 | blood_pressure           |                     3 |   sbp |      2.3 |
|    2 | blood_pressure           |                     3 |   dbp |     22.3 |
|    2 | laboratory               |                     4 |   lab |      bb4 |
|    2 | laboratory               |                     4 |  conc |  2.4 ppm |

As mentioned above, there isn't a universally good way to combine Tables 1, 3a, and 3b into a single rectangle because the rows represent different things.  When forced to combine the different entities, the best option is probably Table 5.

**Table 5: mishmashed grain** is how the points are returned from REDCap if you request the data in a single call.

| `pt` | `repeat`<br>`instrument` | `repeat`<br>`instance` | `height` | `weight` | `bmi` | `sbp` | `dbp` | `lab` |  `conc` |
| ---- | :----------------------: | ---------------------: | -------: | -------: | ----: | ----: | ----: | ----: | ------: |
|    1 |                       -- |                     -- |      1.0 |     11.0 | 111.0 |    -- |    -- |    -- |      -- |
|    1 | blood_pressure           |                      1 |       -- |       -- |    -- |   1.1 |  11.1 |    -- |      -- |
|    1 | blood_pressure           |                      2 |       -- |       -- |    -- |   1.2 |  11.2 |    -- |      -- |
|    1 | blood_pressure           |                      3 |       -- |       -- |    -- |   1.3 |  11.3 |    -- |      -- |
|    1 | laboratory               |                      3 |       -- |       -- |    -- |    -- |    -- |   aa3 | 1.3 ppm |
|    1 | laboratory               |                      4 |       -- |       -- |    -- |    -- |    -- |   aa4 | 1.4 ppm |
|    2 |                       -- |                     -- |      2.0 |     22.0 | 222.0 |    -- |    -- |    -- |      -- |
|    2 | blood_pressure           |                      1 |       -- |       -- |    -- |   2.1 |  22.1 |    -- |      -- |
|    2 | blood_pressure           |                      2 |       -- |       -- |    -- |   2.2 |  22.2 |    -- |      -- |
|    2 | blood_pressure           |                      3 |       -- |       -- |    -- |   2.3 |  22.3 |    -- |      -- |
|    2 | laboratory               |                      3 |       -- |       -- |    -- |    -- |    -- |   bb3 | 2.3 ppm |
|    2 | laboratory               |                      4 |       -- |       -- |    -- |    -- |    -- |   bb4 | 2.4 ppm |

Retrieving from REDCap
==================================================================

When provided a structure like Table 5, some people will initially try to break it apart to resemble Tables 1, 3a, & 3b.  However our advice is to step back and modify how the information is retrieved.  Like other database systems, request the three tables separately from the server and then combine them on your desktop to fit your analyses.

You should choose between two approaches: (a) a single call to REDCapTidieR or (b) multiple calls to REDCapR's [redcap_read()].

Single REDCapTidieR Calls
------------------------------------------------------------------

REDCapTidieR's initial motivation is to facilitate longitudinal analyses and promote [tidy] data hygiene.

Multiple REDCapR Calls
------------------------------------------------------------------

Under the hood, REDCapTidieR calls REDCapR multiple times.

Choosing between the Approaches
------------------------------------------------------------------

We recommend calling REDCapTidieR a single time if

* you are new to data management with R, or
* your analyses will eventually use most of the dataset, or
* you'd benefit from some of the auxiliary information in provides, such as the column and row count of each table.

Calling REDCapR multiple times requires more development time, but could be worth your effort if:

* you are comfortable with data management with R, or
* your analyses require only a fraction of the data (such as (a) you need only the first event, or (b) the analyses don't involve most of the instruments).

If you're somewhere in between, start with REDCapTidieR.  Switch to REDCapR if the operation is taking too long and can be decreased by reducing the amount of information retrieved from the server and transported across the network.