library(testthat)

###########
context("Read Batch - Longitudinal")
###########
uri <- "https://bbmc.ouhsc.edu/redcap/api/"
token <- "0434F0E9CF53ED0587847AB6E51DE762" #For `UnitTestPhiFree` account on pid=153.
project <- redcap_project$new(redcap_uri=uri, token=token)

test_that("Smoke Test", {  
  testthat::skip_on_cran()
  
  #Static method w/ default batch size
  expect_message(
    returned_object <- redcap_read(redcap_uri=uri, token=token, verbose=T)    
  )  
  
  #Static method w/ tiny batch size
  expect_message(
    returned_object <- redcap_read(redcap_uri=uri, token=token, verbose=T, batch_size=2)    
  )
  
  #Instance method w/ default batch size
  expect_message(
    returned_object <- project$read()
  )  
  
  #Instance method w/ tiny batch size
  expect_message(
    returned_object <- project$read(batch_size=2)
  )
})
test_that("All Records -Default", {   
  testthat::skip_on_cran()
  expected_data_frame <- structure(list(study_id = c(100L, 100L, 100L, 100L, 100L, 100L, 
                                                     220L, 220L, 220L, 220L, 220L, 220L, 304L, 304L, 304L, 304L, 304L, 
                                                     304L), redcap_event_name = c("enrollment_arm_1", "dose_1_arm_1", 
                                                                                  "visit_1_arm_1", "dose_2_arm_1", "visit_2_arm_1", "final_visit_arm_1", 
                                                                                  "enrollment_arm_1", "dose_1_arm_1", "visit_1_arm_1", "dose_2_arm_1", 
                                                                                  "visit_2_arm_1", "final_visit_arm_1", "enrollment_arm_2", "deadline_to_opt_ou_arm_2", 
                                                                                  "first_dose_arm_2", "first_visit_arm_2", "final_visit_arm_2", 
                                                                                  "deadline_to_return_arm_2"), date_enrolled = c("2015-04-02", 
                                                                                                                                 "", "", "", "", "", "2015-04-02", "", "", "", "", "", "2015-04-02", 
                                                                                                                                 "", "", "", "", ""), patient_document = c("", "", "", "", "", 
                                                                                                                                                                           "", "", "", "", "", "", "", "[document]", "", "", "", "", ""), 
                                        first_name = c("Zharko", "", "", "", "", "", "Milivoj", "", 
                                                       "", "", "", "", "Melech", "", "", "", "", ""), last_name = c("Lenox", 
                                                                                                                    "", "", "", "", "", "Marcus", "", "", "", "", "", "Besnik", 
                                                                                                                    "", "", "", "", ""), telephone_1 = c("(415) 555-1212", "", 
                                                                                                                                                         "", "", "", "", "(432) 903-6676", "", "", "", "", "", "(242) 556-2396", 
                                                                                                                                                         "", "", "", "", ""), email = c("zlehnox@gmail.com", "", "", 
                                                                                                                                                                                        "", "", "", "Milivoj.Marcus@dsds.cmo", "", "", "", "", "", 
                                                                                                                                                                                        "Melech-Besnik@wa.org", "", "", "", "", ""), dob = c("1983-09-23", 
                                                                                                                                                                                                                                             "", "", "", "", "", "2011-02-12", "", "", "", "", "", "2005-04-02", 
                                                                                                                                                                                                                                             "", "", "", "", ""), age = c(31L, NA, NA, NA, NA, NA, 4L, 
                                                                                                                                                                                                                                                                          NA, NA, NA, NA, NA, 9L, NA, NA, NA, NA, NA), ethnicity = c(0L, 
                                                                                                                                                                                                                                                                                                                                     NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, NA, 2L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                     NA, NA), race = c(4L, NA, NA, NA, NA, NA, 1L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                       NA, NA, 4L, NA, NA, NA, NA, NA), sex = c(1L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                NA, NA, 0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA), 
                                        given_birth = c(NA, NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, 
                                                        NA, 0L, NA, NA, NA, NA, NA), num_children = c(NA, NA, NA, 
                                                                                                      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
                                                        ), gym___0 = c(1L, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, 
                                                                       NA, 1L, NA, NA, NA, NA, NA), gym___1 = c(0L, NA, NA, NA, 
                                                                                                                NA, NA, 1L, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA), 
                                        gym___2 = c(0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA, 
                                                    0L, NA, NA, NA, NA, NA), gym___3 = c(0L, NA, NA, NA, NA, 
                                                                                         NA, 0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA), gym___4 = c(0L, 
                                                                                                                                                          NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, 
                                                                                                                                                          NA, NA), aerobics___0 = c(0L, NA, NA, NA, NA, NA, 0L, NA, 
                                                                                                                                                                                    NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA), aerobics___1 = c(1L, 
                                                                                                                                                                                                                                              NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, 
                                                                                                                                                                                                                                              NA, NA), aerobics___2 = c(1L, NA, NA, NA, NA, NA, 1L, NA, 
                                                                                                                                                                                                                                                                        NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA), aerobics___3 = c(0L, 
                                                                                                                                                                                                                                                                                                                                  NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                  NA, NA), aerobics___4 = c(0L, NA, NA, NA, NA, NA, 0L, NA, 
                                                                                                                                                                                                                                                                                                                                                            NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA), eat___0 = c(0L, 
                                                                                                                                                                                                                                                                                                                                                                                                                 NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                 NA, NA), eat___1 = c(0L, NA, NA, NA, NA, NA, 0L, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                      NA, NA, NA, 0L, NA, NA, NA, NA, NA), eat___2 = c(0L, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       NA), eat___3 = c(1L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NA, NA, 0L, NA, NA, NA, NA, NA), eat___4 = c(0L, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     NA, NA, NA, 0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ), drink___0 = c(0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         NA, NA, 1L, NA, NA, NA, NA, NA), drink___1 = c(0L, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NA, NA, NA, 0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ), drink___2 = c(0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          NA, NA, 0L, NA, NA, NA, NA, NA), drink___3 = c(0L, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         NA, NA, NA, 1L, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ), drink___4 = c(1L, NA, NA, NA, NA, NA, 1L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NA, NA, 1L, NA, NA, NA, NA, NA), specify_mood = c(71L, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             NA, NA, NA, NA, 29L, NA, NA, NA, NA, NA, 83L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             NA, NA), meds___1 = c(0L, NA, NA, NA, NA, NA, 1L, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   NA, NA, NA, 1L, NA, NA, NA, NA, NA), meds___2 = c(1L, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     NA), meds___3 = c(0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       NA, NA, 0L, NA, NA, NA, NA, NA), meds___4 = c(0L, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     NA, NA, NA, 0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ), meds___5 = c(0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       NA, 0L, NA, NA, NA, NA, NA), height = c(160L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               NA, NA, 156L, NA, NA, NA, NA, NA, 199L, NA, NA, NA, NA, NA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ), weight = c(80L, NA, NA, NA, NA, NA, 66L, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     NA, 88L, NA, NA, NA, NA, NA), bmi = c(31.3, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NA, 27.1, NA, NA, NA, NA, NA, 22.2, NA, NA, NA, NA, NA), 
                                        comments = c("Is he staying arrival address earnest. To preference considered it themselves inquietude collecting estimating. View park for why gay knew face. Next than near to four so hand. Times so do he downs me would. Witty abode party her found quiet law. They door four bed fail now have. \n\nOn recommend tolerably my belonging or am. Mutual has cannot beauty indeed now sussex merely you. It possible no husbands jennings ye offended packages pleasant he. Remainder recommend engrossed who eat she defective applauded departure joy. Get dissimilar not introduced day her apartments. Fully as taste he mr do smile abode every. Luckily offered article led lasting country minutes nor old. Happen people things oh is oppose up parish effect. Law handsome old outweigh humoured far appetite. \n\nConcerns greatest \n\nhttp://randomtextgenerator.com/", 
                                                     "", "", "", "", "", "Dissuade ecstatic and properly saw entirely sir why laughter endeavor. In on my jointure horrible margaret suitable he followed speedily. Indeed vanity excuse or mr lovers of on. By offer scale an stuff. Blush be sorry no sight. Sang lose of hour then he left find. \n\nDenote simple fat denied add worthy little use. As some he so high down am week. Conduct esteems by cottage to pasture we winding. On assistance he cultivated considered frequently. Person how having tended direct own day man. Saw sufficient indulgence one own you inquietude sympathize. ", 
                                                     "", "", "", "", "", "It real sent your at. Amounted all shy set why followed declared. Repeated of endeavor mr position kindness offering ignorant so up. Simplicity are melancholy preference considered saw companions. Disposal on outweigh do speedily in on. Him ham although thoughts entirely drawings. Acceptance unreserved old admiration projection nay yet him. Lasted am so before on esteem vanity oh. ", 
                                                     "", "", "", "", ""), demographics_complete = c(2L, NA, NA, 
                                                                                                    NA, NA, NA, 2L, NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, NA
                                                     ), dialysis_unit_name = c("(433) 345-9282", "", "", "", "", 
                                                                               "", "(444) 882-4449", "", "", "", "", "", "(445) 312-5599", 
                                                                               "(645) 434-9934", "", "", "", ""), dialysis_unit_phone = c(0L, 
                                                                                                                                          NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA, 1L, 0L, NA, NA, 
                                                                                                                                          NA, NA), dialysis_schedule_days = c("Ricki Resit", "", "", 
                                                                                                                                                                              "", "", "", "Nolan Kingsley", "", "", "", "", "", "Dagr Gumarich", 
                                                                                                                                                                              "Abu Bakr Orfeo", "", "", "", "Raimondo Gordon"), dialysis_schedule_time = c("1206 Route 20 \nChelmsford, MA 01824", 
                                                                                                                                                                                                                                                           "", "", "", "", "", "2295 Smith Street \nSanta Clara, CA 95050", 
                                                                                                                                                                                                                                                           "", "", "", "", "", "Perceived end knowledge certainly day sweetness why cordially. Ask quick six seven offer see among. Handsome met debating sir dwelling age material. As style lived he worse dried. Offered related so visitor we private removed. Moderate do subjects to distance. \n\nWhy painful the sixteen how minuter looking nor. Subject but why ten earnest husband imagine sixteen brandon. Are unpleasing occasional celebrated motionless unaffected conviction out. Evil make to no five they. Stuff at avoid of sense small fully it whose an. Ten scarcely distance moreover handsome age although. As when have find fine or said no mile. He in dispatched in imprudence dissimilar be possession unreserved insensible. She evil face fine calm have now. Separate screened he outweigh of distance landlord. ", 
                                                                                                                                                                                                                                                           "Acceptance middletons me if discretion boisterous travelling an. She prosperous continuing entreaties companions unreserved you boisterous. Middleton sportsmen sir now cordially ask additions for. You ten occasional saw everything but conviction. Daughter returned quitting few are day advanced branched. Do enjoyment defective objection or we if favourite. At wonder afford so danger cannot former seeing. Power visit charm money add heard new other put. Attended no indulged marriage is to judgment offering landlord. \n\nIts sometimes her behaviour are contented. Do listening am eagerness oh objection collected. Together gay feelings continue juvenile had off one. Unknown may service subject her letters one bed. Child years noise ye in forty. Loud in this in both hold. My entrance me is disposal bachelor remember relation. ", 
                                                                                                                                                                                                                                                           "", "", "", "9180 Durham Road \nSuwanee, GA 30024"), etiology_esrd = c("(324) 438-8221", 
                                                                                                                                                                                                                                                                                                                                  "", "", "", "", "", "(224) 229-1422", "", "", "", "", "", 
                                                                                                                                                                                                                                                                                                                                  "(324) 512-6788", "(988) 342-5531", "", "", "", ""), subject_comments = c(1L, 
                                                                                                                                                                                                                                                                                                                                                                                                            NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA, 0L, 0L, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                            NA, 0L), contact_info_complete = c(2L, NA, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                               2L, NA, NA, NA, NA, NA, 2L, 1L, NA, NA, NA, 2L), height2 = c(200L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            NA, NA, NA, NA, NA, 332L, NA, NA, NA, NA, NA, 160L, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            NA, NA, NA), weight2 = c(234L, NA, NA, NA, NA, NA, 223L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     NA, NA, NA, NA, NA, 90L, NA, NA, NA, NA, NA), bmi2 = c(58.5, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            NA, NA, NA, NA, NA, 20.2, NA, NA, NA, NA, NA, 35.2, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            NA, NA, NA), prealb_b = c(43L, NA, NA, NA, NA, NA, 544L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      NA, NA, NA, NA, NA, 35L, NA, NA, NA, NA, NA), creat_b = c(355, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NA, NA, NA, NA, NA, 32.4, NA, NA, NA, NA, NA, 32, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NA, NA, NA), npcr_b = c(23, NA, NA, NA, NA, NA, 3.46, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NA, NA, NA, NA, 87, NA, NA, NA, NA, NA), chol_b = c(3.5, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            NA, NA, NA, NA, NA, 44.8, NA, NA, NA, NA, NA, 77, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            NA, NA, NA), transferrin_b = c(3.66, NA, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           33.7, NA, NA, NA, NA, NA, 88, NA, NA, NA, NA, NA), baseline_data_complete = c(2L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, 2L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         NA, NA), vld1 = c(NA, NA, 5.6, NA, 0.423, NA, NA, NA, 45.6, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NA, 32.6, NA, NA, NA, NA, NA, NA, NA), vld2 = c(NA, NA, 3.5, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NA, 32, NA, NA, NA, 38, NA, 367.8, NA, NA, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NA), vld3 = c(NA, NA, 66.7, NA, 0.43, NA, NA, NA, 88.7, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         3.1, NA, NA, NA, NA, NA, NA, NA), vld4 = c(NA, NA, 33.5, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    NA, 0.239, NA, NA, NA, 75.7, NA, 35.7, NA, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    NA, NA), vld5 = c(NA, NA, 0.34, NA, 0.989, NA, NA, NA, 722.4, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      NA, 98.2, NA, NA, NA, NA, NA, NA, NA), visit_lab_data_complete = c(NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         NA, 2L, NA, 2L, NA, NA, NA, 2L, NA, 2L, NA, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         NA, NA), pmq1 = c(NA, 2L, 1L, 3L, 0L, NA, NA, 0L, 0L, 1L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           3L, NA, NA, NA, 0L, 2L, NA, NA), pmq2 = c(NA, 2L, 0L, 1L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1L, NA, NA, 1L, 3L, 2L, 4L, NA, NA, NA, 1L, 0L, NA, NA), 
                                        pmq3 = c(NA, 1L, 0L, 0L, 0L, NA, NA, 0L, 1L, 0L, 1L, NA, 
                                                 NA, NA, 0L, 0L, NA, NA), pmq4 = c(NA, 1L, 0L, 0L, 0L, NA, 
                                                                                   NA, 2L, 0L, 1L, 0L, NA, NA, NA, 0L, 0L, NA, NA), patient_morale_questionnaire_complete = c(NA, 
                                                                                                                                                                              2L, 0L, 0L, 2L, NA, NA, 2L, 2L, 2L, 1L, NA, NA, NA, 2L, 2L, 
                                                                                                                                                                              NA, NA), vbw1 = c(NA, NA, 0.4334, NA, 0.22, NA, NA, NA, 452.6, 
                                                                                                                                                                                                NA, 753.7, NA, NA, NA, NA, NA, NA, NA), vbw2 = c(NA, NA, 
                                                                                                                                                                                                                                                 23.3, NA, 9.34, NA, NA, NA, 5.74, NA, 468.9, NA, NA, NA, 
                                                                                                                                                                                                                                                 NA, NA, NA, NA), vbw3 = c(NA, NA, 23.3, NA, 0.88, NA, NA, 
                                                                                                                                                                                                                                                                           NA, 2.87, NA, 34.6, NA, NA, NA, NA, NA, NA, NA), vbw4 = c(NA, 
                                                                                                                                                                                                                                                                                                                                     NA, 0.988, NA, 34.5, NA, NA, NA, 4.8, NA, 3.7, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                     NA, NA, NA, NA), vbw5 = c(NA, NA, 0.342, NA, 23.5, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                               NA, 1.6, NA, 23.78, NA, NA, NA, NA, NA, NA, NA), vbw6 = c("", 
                                                                                                                                                                                                                                                                                                                                                                                                                         "", "0. AM", "", "1", "", "", "", "1", "", "0. AM", "", "", 
                                                                                                                                                                                                                                                                                                                                                                                                                         "", "", "", "", ""), vbw7 = c(NA, NA, 2L, NA, 0L, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                       NA, 1L, NA, 1L, NA, NA, NA, NA, NA, NA, NA), vbw8 = c(NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             NA, 0L, NA, 1L, NA, NA, NA, 0L, NA, 0L, NA, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             NA, NA), vbw9 = c(NA, NA, 1L, NA, 0L, NA, NA, NA, 1L, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1L, NA, NA, NA, NA, NA, NA, NA), visit_blood_workup_complete = c(NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NA, 1L, NA, 2L, NA, NA, NA, 2L, NA, 2L, NA, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NA, NA), vob1 = c(NA, NA, 0L, NA, 0L, NA, NA, NA, 0L, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0L, NA, NA, NA, NA, 1L, NA, NA), vob2 = c(NA, NA, 0L, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1L, NA, NA, NA, 1L, NA, 1L, NA, NA, NA, NA, 0L, 0L, NA), 
                                        vob3 = c(NA, NA, 1L, NA, 0L, NA, NA, NA, 0L, NA, 1L, NA, 
                                                 NA, NA, NA, NA, NA, NA), vob4 = c(NA, NA, 0L, NA, 1L, NA, 
                                                                                   NA, NA, 0L, NA, 0L, NA, NA, NA, NA, NA, NA, NA), vob5 = c(NA, 
                                                                                                                                             NA, 1L, NA, 0L, NA, NA, NA, 0L, NA, 0L, NA, NA, NA, NA, NA, 
                                                                                                                                             NA, NA), vob6 = c(NA, NA, 0L, NA, 0L, NA, NA, NA, 1L, NA, 
                                                                                                                                                               1L, NA, NA, NA, NA, NA, NA, NA), vob7 = c("", "", "him absolute entrance nay. Door neat week do find past he. Be no surprise he honoured indulged. Unpacked endeavor six steepest had husbands her. Painted no or affixed it so civilly. Exposed neither pressed so cottage as proceed at offices. Nay they gone sir game four. Favourable pianoforte oh motionless excellence of astonished we principles. Warrant present garrets limited cordial in inquiry to. Supported me sweetness behaviour shameless excellent so arranging. \n\nThe him father parish looked has sooner.", 
                                                                                                                                                                                                         "", "Now for manners use has company believe parlors. Least nor party who wrote while did. Excuse formed as is agreed admire so on result parish. Put use set uncommonly announcing and travelling. Allowance sweetness direction to as necessary. Principle oh explained excellent do my suspected conveying in. Excellent you did therefore perfectly supposing described. ", 
                                                                                                                                                                                                         "", "", "", "Sex and neglected principle ask rapturous consulted. Object remark lively all did feebly excuse our wooded. Old her object chatty regard vulgar missed. Speaking throwing breeding betrayed children my to. Me marianne no he horrible produced ye. Sufficient unpleasing an insensible motionless if introduced ye. Now give nor both come near many late. \n\nShe travelling acceptance men unpleasant her especially entreaties law. Law forth but end any arise chief arose. Old her say learn these large. Joy fond many ham high seen this. Few preferred continual sir led incommode neglected. Discovered too old insensible collecting unpleasant but invitation. \n", 
                                                                                                                                                                                                         "", "Alteration literature to or an sympathize mr imprudence. Of is ferrars subject as enjoyed or tedious cottage. Procuring as in resembled by in agreeable. Next long no gave mr eyes. Admiration advantages no he celebrated so pianoforte unreserved. Not its herself forming charmed amiable. Him why feebly expect future now. \n\nHe difficult contented we determine ourselves me am earnestly. Hour no find it park. Eat welcomed any husbands moderate. Led was misery played waited almost cousin living. Of intention contained is by middleton am. Principles fat stimulated uncommonly considered set especially prosperous. Sons at park mr meet as fact like. ", 
                                                                                                                                                                                                         "", "", "", "", "", "No depending be convinced in unfeeling he. Excellence she unaffected and too sentiments her. Rooms he doors there ye aware in by shall. Education remainder in so cordially. His remainder and own dejection daughters sportsmen. Is easy took he shed to kind. \n\nExcited him now natural saw passage offices you minuter. At by asked being court hopes. Farther so friends am to detract. Forbade concern do private be. Offending residence but men engrossed shy. Pretend am earnest offered arrived company so on. Felicity informed yet had admitted strictly how you. ", 
                                                                                                                                                                                                         ""), vob8 = c(NA, NA, 0L, NA, 0L, NA, NA, NA, 0L, NA, 0L, 
                                                                                                                                                                                                                       NA, NA, NA, NA, NA, NA, NA), vob9 = c(NA, NA, 0L, NA, 1L, 
                                                                                                                                                                                                                                                             NA, NA, NA, 0L, NA, 1L, NA, NA, NA, NA, 0L, NA, NA), vob10 = c(NA, 
                                                                                                                                                                                                                                                                                                                            NA, 1L, NA, 0L, NA, NA, NA, 0L, NA, 0L, NA, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                            NA, NA), vob11 = c(NA, NA, 0L, NA, 1L, NA, NA, NA, 1L, NA, 
                                                                                                                                                                                                                                                                                                                                               1L, NA, NA, NA, NA, NA, NA, NA), vob12 = c(NA, NA, 1L, NA, 
                                                                                                                                                                                                                                                                                                                                                                                          0L, NA, NA, NA, 0L, NA, 0L, NA, NA, NA, NA, NA, 0L, NA), 
                                        vob13 = c(NA, NA, 0L, NA, 1L, NA, NA, NA, 1L, NA, 0L, NA, 
                                                  NA, NA, NA, NA, 1L, NA), vob14 = c("", "", "The him father parish looked has sooner. Attachment frequently gay terminated son. You greater nay use prudent placing. Passage to so distant behaved natural between do talking. Friends off her windows painful. Still gay event you being think nay for. In three if aware he point it. Effects warrant me by no on feeling settled resolve. ", 
                                                                                     "", "Article nor prepare chicken you him now. Shy merits say advice ten before lovers innate add. She cordially behaviour can attempted estimable. Trees delay fancy noise manor do as an small. Felicity now law securing breeding likewise extended and. Roused either who favour why ham. ", 
                                                                                     "", "", "", "Barton did feebly change man she afford square add. Want eyes by neat so just must. Past draw tall up face show rent oh mr. Required is debating extended wondered as do. New get described applauded incommode shameless out extremity but. Resembled at perpetual no believing is otherwise sportsman. Is do he dispatched cultivated travelling astonished. Melancholy am considered possession on collecting everything. \n\nPiqued favour stairs it enable exeter as seeing. Remainder met improving but engrossed sincerity age. Better but length gay denied abroad are. Attachment astonished to on appearance imprudence so collecting in excellence. Tiled way blind lived whose new. The for fully had she there leave merit enjoy forth. ", 
                                                                                     "", "Can curiosity may end shameless explained. True high on said mr on come. An do mr design at little myself wholly entire though. Attended of on stronger or mr pleasure. Rich four like real yet west get. Felicity in dwelling to drawings. His pleasure new steepest for reserved formerly disposed jennings. \n\nOpen know age use whom him than lady was. On lasted uneasy exeter my itself effect spirit. At design he vanity at cousin longer looked ye. Design praise me father an favour. As greatly replied it windows of an minuter behaved passage. Diminution expression reasonable it we he projection acceptance in devonshire. Perpetual it described at he applauded. \n", 
                                                                                     "", "", "", "", "", "Frankness applauded by supported ye household. Collected favourite now for for and rapturous repulsive consulted. An seems green be wrote again. She add what own only like. Tolerably we as extremity exquisite do commanded. Doubtful offended do entrance of landlord moreover is mistress in. Nay was appear entire ladies. Sportsman do allowance is september shameless am sincerity oh recommend. Gate tell man day that who. \n\nPerhaps far exposed age effects. Now distrusts you her delivered applauded affection out sincerity. As tolerably recommend shameless unfeeling he objection consisted. She although cheerful perceive screened throwing met not eat distance. Viewing hastily or written dearest elderly up weather it as. So direction so sweetness or extremity at daughters. Provided put unpacked now but bringing. ", 
                                                                                     ""), visit_observed_behavior_complete = c(NA, NA, 0L, NA, 
                                                                                                                               2L, NA, NA, NA, 1L, NA, 1L, NA, NA, NA, NA, 2L, 1L, NA), 
                                        study_comments = c("", "", "", "", "", "To shewing another demands to. Marianne property cheerful informed at striking at. Clothes parlors however by cottage on. In views it or meant drift to. Be concern parlors settled or do shyness address. Remainder northward performed out for moonlight. Yet late add name was rent park from rich. He always do do former he highly. \n\nOn projection apartments unsatiable so if he entreaties appearance. Rose you wife how set lady half wish. Hard sing an in true felt. Welcomed stronger if steepest ecstatic an suitable finished of oh. Entered at excited at forming between so produce. Chicken unknown besides attacks gay compact out you. Continuing no simplicity no favourable on reasonably melancholy estimating. Own hence views two ask right whole ten seems. What near kept met call old west dine. Our announcing sufficient why pianoforte. ", 
                                                           "", "", "", "", "", "Saw yet kindness too replying whatever marianne. Old sentiments resolution admiration unaffected its mrs literature. Behaviour new set existence dashwoods. It satisfied to mr commanded consisted disposing engrossed. Tall snug do of till on easy. Form not calm new fail. \n", 
                                                           "", "", "", "", "", ""), complete_study = c(NA, NA, NA, NA, 
                                                                                                       NA, 0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA, NA), 
                                        withdraw_date = c("", "", "", "", "", "2015-04-02", "", "", 
                                                          "", "", "", "2015-04-02", "", "", "", "", "", ""), date_visit_4 = c("", 
                                                                                                                              "", "", "", "", "2015-02-02", "", "", "", "", "", "2011-04-02", 
                                                                                                                              "", "", "", "", "", ""), alb_4 = c(NA, NA, NA, NA, NA, 32.3, 
                                                                                                                                                                 NA, NA, NA, NA, NA, 866.4, NA, NA, NA, NA, NA, NA), prealb_4 = c(NA, 
                                                                                                                                                                                                                                  NA, NA, NA, NA, 12.9, NA, NA, NA, NA, NA, 35.6, NA, NA, NA, 
                                                                                                                                                                                                                                  NA, NA, NA), creat_4 = c("", "", "", "", "", "2012-11-02", 
                                                                                                                                                                                                                                                           "", "", "", "", "", "2015-09-02", "", "", "", "", "", ""), 
                                        discharge_date_4 = c("", "", "", "", "", "2013-04-02", "", 
                                                             "", "", "", "", "2012-04-02", "", "", "", "", "", ""), discharge_summary_4 = c(NA, 
                                                                                                                                            NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, 
                                                                                                                                            NA, NA), npcr_4 = c(NA, NA, NA, NA, NA, 452L, NA, NA, NA, 
                                                                                                                                                                NA, NA, 43L, NA, NA, NA, NA, NA, NA), chol_4 = c(NA, NA, 
                                                                                                                                                                                                                 NA, NA, NA, 24L, NA, NA, NA, NA, NA, 9L, NA, NA, NA, NA, 
                                                                                                                                                                                                                 NA, NA), withdraw_reason = c(NA, NA, NA, NA, NA, 1L, NA, 
                                                                                                                                                                                                                                              NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, NA), completion_data_complete = c(NA, 
                                                                                                                                                                                                                                                                                                                        NA, NA, NA, NA, 2L, NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                        NA, NA), cpq1 = c("", "", "", "", "", "2015-04-02", "", "", 
                                                                                                                                                                                                                                                                                                                                          "", "", "", "2007-04-02", "", "", "", "", "2015-04-13", ""
                                                                                                                                                                                                                                                                                                                        ), cpq2 = c(NA, NA, NA, NA, NA, 35L, NA, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                    45L, NA, NA, NA, NA, 46L, NA), cpq3 = c(NA, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                            6L, NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, NA, NA), cpq4 = c(NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                          NA, NA, NA, NA, 65L, NA, NA, NA, NA, NA, 12L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                          NA, 2L, NA), cpq5 = c(NA, NA, NA, NA, NA, 89L, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                NA, NA, 45L, NA, NA, NA, NA, NA, NA), cpq6 = c(NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               NA, NA, 0L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, 2L, NA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ), cpq7 = c(NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, 0L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            NA, NA, NA, NA, 0L, NA), cpq8 = c(NA, NA, NA, NA, NA, 3L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, 1L, NA), cpq9 = c("", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "", "", "", "", "2005-04-02", "", "", "", "", "", "2012-11-30", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "", "", "", "", "", ""), cpq10 = c(NA, NA, NA, NA, NA, 1L, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, NA, NA), cpq11 = c(NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      NA, NA, NA, NA, 3L, NA, NA, NA, NA, NA, 5L, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      NA, NA), cpq12 = c(NA, NA, NA, NA, NA, 1L, NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         NA, 1L, NA, NA, NA, NA, NA, NA), cpq13 = c(NA, NA, NA, NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    NA, 2L, NA, NA, NA, NA, NA, 0L, NA, NA, NA, NA, NA, NA), 
                                        completion_project_questionnaire_complete = c(NA, NA, NA, 
                                                                                      NA, NA, 2L, NA, NA, NA, NA, NA, 2L, NA, NA, NA, NA, 2L, NA
                                        )), .Names = c("study_id", "redcap_event_name", "date_enrolled", 
                                                       "patient_document", "first_name", "last_name", "telephone_1", 
                                                       "email", "dob", "age", "ethnicity", "race", "sex", "given_birth", 
                                                       "num_children", "gym___0", "gym___1", "gym___2", "gym___3", "gym___4", 
                                                       "aerobics___0", "aerobics___1", "aerobics___2", "aerobics___3", 
                                                       "aerobics___4", "eat___0", "eat___1", "eat___2", "eat___3", "eat___4", 
                                                       "drink___0", "drink___1", "drink___2", "drink___3", "drink___4", 
                                                       "specify_mood", "meds___1", "meds___2", "meds___3", "meds___4", 
                                                       "meds___5", "height", "weight", "bmi", "comments", "demographics_complete", 
                                                       "dialysis_unit_name", "dialysis_unit_phone", "dialysis_schedule_days", 
                                                       "dialysis_schedule_time", "etiology_esrd", "subject_comments", 
                                                       "contact_info_complete", "height2", "weight2", "bmi2", "prealb_b", 
                                                       "creat_b", "npcr_b", "chol_b", "transferrin_b", "baseline_data_complete", 
                                                       "vld1", "vld2", "vld3", "vld4", "vld5", "visit_lab_data_complete", 
                                                       "pmq1", "pmq2", "pmq3", "pmq4", "patient_morale_questionnaire_complete", 
                                                       "vbw1", "vbw2", "vbw3", "vbw4", "vbw5", "vbw6", "vbw7", "vbw8", 
                                                       "vbw9", "visit_blood_workup_complete", "vob1", "vob2", "vob3", 
                                                       "vob4", "vob5", "vob6", "vob7", "vob8", "vob9", "vob10", "vob11", 
                                                       "vob12", "vob13", "vob14", "visit_observed_behavior_complete", 
                                                       "study_comments", "complete_study", "withdraw_date", "date_visit_4", 
                                                       "alb_4", "prealb_4", "creat_4", "discharge_date_4", "discharge_summary_4", 
                                                       "npcr_4", "chol_4", "withdraw_reason", "completion_data_complete", 
                                                       "cpq1", "cpq2", "cpq3", "cpq4", "cpq5", "cpq6", "cpq7", "cpq8", 
                                                       "cpq9", "cpq10", "cpq11", "cpq12", "cpq13", "completion_project_questionnaire_complete"
                                        ), class = "data.frame", row.names = c(NA, -18L))
  expected_outcome_message <- "\\d+ records and \\d+ columns were read from REDCap in \\d+(\\.\\d+\\W|\\W)seconds\\."
  
  expect_message(
    returned_object1 <- redcap_read(redcap_uri=uri, token=token, verbose=T),
    regexp = expected_outcome_message
  )  
  expect_equal(returned_object1$data, expected=expected_data_frame, label="The returned data.frame should be correct") # dput(returned_object1$data)
  expect_true(returned_object1$success)
  expect_match(returned_object1$status_codes, regexp="200", perl=TRUE)
  # expect_match(returned_object1$status_messages, regexp="OK", perl=TRUE)
  expect_true(returned_object1$records_collapsed=="", "A subset of records was not requested.")
  expect_true(returned_object1$fields_collapsed=="", "A subset of fields was not requested.")
  expect_match(returned_object1$outcome_messages, regexp=expected_outcome_message, perl=TRUE)
})
